### ISSUE TITLE
PHPStan fails because DrupalFinder relies on composer.json properties to detect DrupalRoot

### ISSUE THREAD

**Issue by gardon** [ddev/ddev-drupal-contrib#42] opened 2024-05-07 14:49 UTC
I was trying to use this to run PHPStan on a contrib project (feeds) and after some debugging I got to webflo/drupal-finder which fails to detect Drupal Root because it loads the composer.json from the module instead, and cannot find the installer-paths property that it uses to detect the root.

**Comment by gardon** [comment] 2024-05-07 14:58
Not sure about the implication, but running `ddev expand-composer-json` allows me to run PHPStan

**Comment by weitzman** [comment] 2024-05-07 15:34
Dupe of #14

**Closed by weitzman** 2024-05-07 15:34 UTC
